#!/usr/bin/env bash
set -euo pipefail

PUBLIC_SITE="$(printf '%s' "${PUBLIC_SITE:-}" | tr '[:upper:]' '[:lower:]' | xargs)"
SITE_VIEW="$(printf '%s' "${SITE_VIEW:-auto}" | tr '[:upper:]' '[:lower:]' | xargs)"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/_site"

write_site_config() {
  local dest="$1"
  local view="$SITE_VIEW"

  case "$view" in
    mobile|desktop) ;;
    *) view="auto" ;;
  esac

  mkdir -p "$dest/js"
  cat > "$dest/js/site-config.js" <<EOF
// Generated by scripts/prepare-site.sh — do not edit in _site
window.FDH_SITE_CONFIG = { defaultView: '$view' };
EOF
}

deploy_full() {
  local dest="$1"
  local keep_gate="${2:-false}"

  mkdir -p "$dest"
  # tar is available on Vercel; rsync is not
  local excludes=(
    --exclude='.git'
    --exclude='_site'
    --exclude='robots-private.txt'
    --exclude='.github'
    --exclude='scripts'
    --exclude='vercel.json'
    --exclude='vercel.public.json'
    --exclude='middleware.js'
  )

  if [ "$keep_gate" != "true" ]; then
    excludes+=(--exclude='coming-soon.html')
  fi

  tar -C "$ROOT" "${excludes[@]}" -cf - . | tar -C "$dest" -xf -
}

deploy_gated() {
  local dest="$1"
  local gate="$ROOT/coming-soon.html"

  rm -rf "$dest"
  mkdir -p "$dest/css" "$dest/js" "$dest/data"

  cp "$gate" "$dest/index.html"
  cp "$gate" "$dest/404.html"

  for page in "$ROOT"/*.html; do
    base="$(basename "$page")"
    [ "$base" = "coming-soon.html" ] && continue
    cp "$gate" "$dest/$base"
  done

  for stale in \
    "$dest/js/site.js" \
    "$dest/js/contact.js" \
    "$dest/js/mobile-ui.js" \
    "$dest/js/schema.js" \
    "$dest/js/providers.js" \
    "$dest/js/trust.js" \
    "$dest/js/book-form.js" \
    "$dest/js/photography.js" \
    "$dest/data/contact.json" \
    "$dest/data/providers.json" \
    "$dest/data/trust.json" \
    "$dest/data/photography.json" \
    "$dest/site.webmanifest" \
    "$dest/sitemap.xml"
  do
    cp "$gate" "$stale"
  done

  cp "$ROOT/css/site.css" "$dest/css/"
  cp "$ROOT/favicon.svg" "$dest/" 2>/dev/null || true
  cp "$ROOT/robots-private.txt" "$dest/robots.txt"
}

rm -rf "$OUT"
mkdir -p "$OUT"

if [ "$PUBLIC_SITE" = "true" ]; then
  echo "PUBLIC_SITE=true — deploying full site"
  deploy_full "$OUT"
elif [ "${GITHUB_PAGES:-}" = "true" ]; then
  echo "PUBLIC_SITE=${PUBLIC_SITE:-<unset>} — GitHub Pages gate deploy"
  deploy_gated "$OUT"
else
  echo "PUBLIC_SITE=${PUBLIC_SITE:-<unset>} — Vercel full site; only floridadayhospital + *.vercel.app allowed via middleware"
  deploy_full "$OUT" true
  cp "$ROOT/robots-private.txt" "$OUT/robots.txt"
fi

write_site_config "$OUT"
echo "SITE_VIEW=${SITE_VIEW} — default view written to _site/js/site-config.js"
